package world

import "image/color"

// Player represents a player in the game world.
type Player struct {
	Username      string      // Player's username
	ID            int         // Player's unique ID
	MobID         ID          // Player's unique mob ID
	VisibleMobIDs []ID        // List of mobs visible to the player
	Color         color.NRGBA // Player's color in NRGBA format
	Count         int         // This is a client-side only field generated by MetaRefresh. It is used for highscore.
}

// NewPlayer makes a new player, wow.
func NewPlayer(user string, id ID, color color.NRGBA) *Player {
	return &Player{
		Username: user,
		ID:       id,
		Color:    color,
	}
}
